version: 2

sources:
  - name : source_bronze
    database: pyspark_proj
    schema: bronze
    tables:
       - name : trips

  - name : source_silver
    database: pyspark_proj
    schema: silver
    tables:
       - name : customers
       - name : drivers
       - name : locations
       - name : payments
       - name : vehicles